{
    "id": "dbpedia_3062_1",
    "rank": 9,
    "data": {
        "url": "https://github.com/invoke-ai/InvokeAI/issues/3048",
        "read_more_link": "",
        "language": "en",
        "title": "[bug]: txt2img got error: Compel.__init__() got an unexpected keyword argument 'truncate_long_prompts' · Issue #3048 · invoke-ai/InvokeAI",
        "top_image": "https://opengraph.githubassets.com/23151b8d5dbbcdb4f821945ad7027497f86fc978585d140f304df2b488901286/invoke-ai/InvokeAI/issues/3048",
        "meta_img": "https://opengraph.githubassets.com/23151b8d5dbbcdb4f821945ad7027497f86fc978585d140f304df2b488901286/invoke-ai/InvokeAI/issues/3048",
        "images": [
            "https://avatars.githubusercontent.com/u/144366?s=40&v=4",
            "https://avatars.githubusercontent.com/u/3386551?s=80&u=08a4edcf6f73c3a25d5f047315584f7a11d819d5&v=4",
            "https://avatars.githubusercontent.com/u/3386551?s=40&u=08a4edcf6f73c3a25d5f047315584f7a11d819d5&v=4",
            "https://avatars.githubusercontent.com/u/31807370?s=40&u=6ed39b71374c5822735eadbde122f6834b4e4322&v=4",
            "https://avatars.githubusercontent.com/u/144366?s=80&v=4",
            "https://avatars.githubusercontent.com/u/3386551?s=80&u=08a4edcf6f73c3a25d5f047315584f7a11d819d5&v=4",
            "https://avatars.githubusercontent.com/u/144366?s=80&v=4",
            "https://avatars.githubusercontent.com/u/3386551?s=80&u=08a4edcf6f73c3a25d5f047315584f7a11d819d5&v=4",
            "https://avatars.githubusercontent.com/u/144366?s=80&v=4",
            "https://avatars.githubusercontent.com/u/31807370?s=40&u=6ed39b71374c5822735eadbde122f6834b4e4322&v=4",
            "https://avatars.githubusercontent.com/u/144366?s=40&v=4",
            "https://avatars.githubusercontent.com/u/144366?s=52&v=4",
            "https://avatars.githubusercontent.com/u/3386551?s=52&v=4",
            "https://avatars.githubusercontent.com/u/31807370?s=52&v=4"
        ],
        "movies": [],
        "keywords": [],
        "meta_keywords": [
            ""
        ],
        "tags": null,
        "authors": [
            "invoke-ai"
        ],
        "publish_date": null,
        "summary": "",
        "meta_description": "Is there an existing issue for this? I have searched the existing issues OS macOS GPU mps MacBookPro: intel CPU with an eGPU(RX 6600 8G) VRAM No response What version did you experience this issue on? 09dfde0 What happened? After run git...",
        "meta_lang": "en",
        "meta_favicon": "https://github.com/fluidicon.png",
        "meta_site_name": "GitHub",
        "canonical_link": "https://github.com/invoke-ai/InvokeAI/issues/3048",
        "text": "Successfully built InvokeAI Installing collected packages: InvokeAI Attempting uninstall: InvokeAI Found existing installation: InvokeAI 3.0.0+a0 Uninstalling InvokeAI-3.0.0+a0: Successfully uninstalled InvokeAI-3.0.0+a0 Successfully installed InvokeAI-3.0.0+a0 (invokeai) ppt@pptdeMacBook-Pro invokeAI % python scripts/invoke.py --web --host 0.0.0.0 OMP: Error #15: Initializing libomp.dylib, but found libiomp5.dylib already initialized. OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/ zsh: abort python scripts/invoke.py --web --host 0.0.0.0 (invokeai) ppt@pptdeMacBook-Pro invokeAI %"
    }
}