{
    "id": "wrong_mix_range_foundationPlace_00007_2",
    "rank": 46,
    "data": {
        "url": "https://stackoverflow.com/questions/72503660/traceback-error-while-creating-a-discord-bot",
        "read_more_link": "",
        "language": "en",
        "title": "Traceback error while creating a discord bot",
        "top_image": "https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded",
        "meta_img": "https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded",
        "images": [
            "https://www.gravatar.com/avatar/bbf02ad0a63c437b466b4ab910bd6b95?s=64&d=identicon&r=PG&f=y&so-version=2",
            "https://www.gravatar.com/avatar/7c0c37c3d8f32defcff5b70aee6e5dd0?s=64&d=identicon&r=PG",
            "https://lh3.googleusercontent.com/a/AATXAJz8OnCBDm6H8ukmtw_a-CVc69JH0xgYLmD9HbK1=k-s64",
            "https://stackoverflow.com/posts/72503660/ivc/4018?prg=3ec433ac-a2e1-463e-89b8-779db1961704"
        ],
        "movies": [],
        "keywords": [],
        "meta_keywords": [
            ""
        ],
        "tags": null,
        "authors": [],
        "publish_date": "2022-06-04T22:52:28",
        "summary": "",
        "meta_description": "I was creating a basic python but and I keep getting this massive traceback error. It was working originally and then I switched up the code a little and got the error. I then tried commenting out ...",
        "meta_lang": "en",
        "meta_favicon": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "meta_site_name": "Stack Overflow",
        "canonical_link": "https://stackoverflow.com/questions/72503660/traceback-error-while-creating-a-discord-bot",
        "text": "I was creating a basic python but and I keep getting this massive traceback error. It was working originally and then I switched up the code a little and got the error. I then tried commenting out what I had written but it still returns this error. What is wrong with it?\n\nfrom discord.ext import commands import os import random #import urllib.request #import json #api = os.environ['ApiKey'] bot = commands.Bot(command_prefix='!') bot.videos = [ 'https://www.youtube.com/watch?v=XmoKM4RunZQ', 'https://www.youtube.com/watch?v=qTmjKpl2Jk0', 'https://www.youtube.com/watch?v=hY7m5jjJ9mM' ] #@bot.command() #async def search(ctx, input): # url = \"https://imdb-api.com/en/API/SearchMovie/\" + api + \"/\" + input; # req = urllib.request.urlopen(url).read().decode() # data = json.loads(req) # await ctx.send(data) @bot.command() async def hello(ctx): await ctx.send(\"hello \" + ctx.author.display_name) @bot.command() async def cat(ctx): await ctx.send(random.choice(bot.videos)) @bot.command() async def happy(ctx, *, item): await ctx.send(\"Awesome!\") bot.happylist.append(item) print(bot.happylist) @bot.command() async def sad(ctx): await ctx.send(\"Hope this makes you feel better!\") await ctx.send(random.choice(bot.happylist)) @bot.command() async def calc(ctx, x: float, fn: str, y: float): if fn == '+': await ctx.send(x + y) elif fn == '-': await ctx.send(x - y) elif fn == '*': await ctx.send(x * y) elif fn == '/': await ctx.send(x / y) else: await ctx.send(\"We only support 4 function operations\") password = os.environ['password'] bot.run(password)\n\nand heres the error:\n\nTraceback (most recent call last): File \"main.py\", line 61, in <module> bot.run(password) File \"/home/runner/chatbot/venv/lib/python3.8/site-packages/discord/client.py\", line 723, in run return future.result() File \"/home/runner/chatbot/venv/lib/python3.8/site-packages/discord/client.py\", line 702, in runner await self.start(*args, **kwargs) File \"/home/runner/chatbot/venv/lib/python3.8/site-packages/discord/client.py\", line 665, in start await self.login(*args, bot=bot) File \"/home/runner/chatbot/venv/lib/python3.8/site-packages/discord/client.py\", line 511, in login await self.http.static_login(token.strip(), bot=bot) File \"/home/runner/chatbot/venv/lib/python3.8/site-packages/discord/http.py\", line 300, in static_login data = await self.request(Route('GET', '/users/@me')) File \"/home/runner/chatbot/venv/lib/python3.8/site-packages/discord/http.py\", line 216, in request raise HTTPException(r, data) discord.errors.HTTPException: 429 Too Many Requests (error code: 0): <!DOCTYPE html> <!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]--> <!--[if IE 7]> <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]--> <!--[if IE 8]> <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]--> <!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]--> <head> <title>Access denied | discord.com used Cloudflare to restrict access</title> <meta charset=\"UTF-8\" /> <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /> <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" /> <meta name=\"robots\" content=\"noindex, nofollow\" /> <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" /> <link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" /> <script> (function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById(\"error-feedback-survey\"),d=document.getElementById(\"error-feedback-success\"),b=new XMLHttpRequest;a={event:\"feedback clicked\",properties:{errorCode:1015,helpful:a,version:1}};b.open(\"POST\",\"https://sparrow.cloudflare.com/api/v1/event\");b.setRequestHeader(\"Content-Type\",\"application/json\");b.setRequestHeader(\"Sparrow-Source-Key\",\"c771f0e4b54944bebf4261d44bd79a1e\"); b.send(JSON.stringify(a));c.classList.add(\"feedback-hidden\");d.classList.remove(\"feedback-hidden\")};document.addEventListener(\"DOMContentLoaded\",function(){var a=document.getElementById(\"error-feedback\"),c=document.getElementById(\"feedback-button-yes\"),d=document.getElementById(\"feedback-button-no\");\"classList\"in a&&(a.classList.remove(\"feedback-hidden\"),c.addEventListener(\"click\",function(){e(!0)}),d.addEventListener(\"click\",function(){e(!1)}))})}})(); </script> <script defer src=\"https://api.radar.cloudflare.com/beacon.js\"></script> <script async src='/cdn-cgi/bm/cv/669835187/api.js'></script></head> <body> <div id=\"cf-wrapper\"> <div class=\"cf-alert cf-alert-error cf-cookie-error hidden\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div> <div id=\"cf-error-details\" class=\"p-0\"> <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased\"> <h1 class=\"inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight\"> <span data-translate=\"error\">Error</span> <span>1015</span> </h1> <span class=\"inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed\">Ray ID: 71643901ee3c139a &bull;</span> <span class=\"inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed\">2022-06-04 22:49:36 UTC</span> <h2 class=\"text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light\">You are being rate limited</h2> </header> <section class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\"> <div id=\"what-happened-section\" class=\"w-1/2 md:w-full\"> <h2 class=\"text-3xl leading-tight font-normal mb-4 text-black-dark antialiased\" data-translate=\"what_happened\">What happened?</h2> <p>The owner of this website (discord.com) has banned you temporarily from accessing this website.</p> </div> </section> <div class=\"feedback-hidden py-8 text-center\" id=\"error-feedback\"> <div id=\"error-feedback-survey\" class=\"footer-line-wrapper\"> Was this page helpful? <button class=\"border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded\" id=\"feedback-button-yes\" type=\"button\">Yes</button> <button class=\"border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded\" id=\"feedback-button-no\" type=\"button\">No</button> </div> <div class=\"feedback-success feedback-hidden\" id=\"error-feedback-success\"> Thank you for your feedback! </div> </div> <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\"> <p class=\"text-13\"> <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">71643901ee3c139a</strong></span> <span class=\"cf-footer-separator sm:hidden\">&bull;</span> <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Your IP</span>: 34.82.250.161</span> <span class=\"cf-footer-separator sm:hidden\">&bull;</span> <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span> </p> </div><!-- /.error-footer --> </div><!-- /#cf-error-details --> </div><!-- /#cf-wrapper --> <script> window._cf_translation = {}; </script> <script type=\"text/javascript\">(function(){window['__CF$cv$params']={r:'71643901ee3c139a',m:'Vy.Q.DAKTQGlwogr5_Zq6mJ.XI.4iEMA73ojP1S.n8M-1654382976-0-AUwTtcSmYDa4yGdhJdUqeOtnKFtpnDuMDaR+h2pVff2tMI6ULgld0SWSU/d3vveoniF166IdrBSWv4R1qWLTzPALqbQgIrH1GxeZO6jzkZivoKOZloO4F0XXm2YJPgu4aGtIoMuh32ckjKLWGOw05zQ=',s:[0xd87400444f,0xe085f22f77],}})();</script></body> </html>\n\nThanks for the help!"
    }
}